language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
env:
- COPILOT_DETECT_OPTIONS="--detect.pip.requirements.path=./requirements.txt"
script:
- pytest
after_success:
- bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
